apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: my-project
spec:
  type: LoadBalancer
  externalIPs: ["34.227.18.120"]
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000